appVersion: app/v1
kind: StatefulSet
metadata:
  name: postgres-statefulset
  namespace: postgres
  labels:
    app: postgres
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:13.3-alpine
        envFrom:
        - configMapRef:
            name: postgres-config
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: pg_pv_volume
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: pg_pv_volume
        persistentVolumeClaim:
          claimName: pg_pv_claim